### ISSUE TITLE
Merge templates into community-repo

### ISSUE THREAD

**Issue by lzap** [RedHatSatellite/satellite6-fips-client#5]
Hey guys,

I see no reason why we keep those templates here. Let's merge them into our community-templates repo. I think the best approach would be to do little refactoring breaking it up into snippets and using those snippets in our default templates we already ship, but if that's too challenging we can keep just these copies in our repo.

@sideangleside @ares @wzzrd

**Comment by ares** [comment]
Didn't this happen already https://github.com/theforeman/community-templates/pull/560?

**Comment by lzap** [comment]
Yeah. https://github.com/RedHatSatellite/satellite6-fips-client/pull/6
